import type { Metadata } from 'next'
import Navbar from './components/ui/Navbar'
import Footer from './components/ui/Footer'
import { CartProvider } from './components/context/CartContext'
import './globals.css'
import { AuthProvider } from './components/context/AuthContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <CartProvider>
            <Navbar />
            {children}
            <Footer />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
